version: '3.5'

networks:
  backend:
    name: "${NETWORK:-preciosrotos}"

volumes:
  mongo:
    name: preciosrotos_mongo

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: preciosrotos_app
    volumes:
      - .:/var/www/preciosrotos
    ports:
      - "${SERVER_HOST_PORT:-3000}:8085"
    depends_on:
       - db
    working_dir: /var/www/preciosrotos
    user: 1000:1000
    command: ["node", '.']
    networks:
      - backend

  db:
    image: mongo:5.0.0
    container_name: preciosrotos_db
    command: mongod --auth
    restart: always
    volumes:
      - mongo:/data/db
      - .docker/mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro
    environment:
      MONGO_INITDB_DATABASE: precios
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - backend